In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np



In [ ]:
Train_data= pd.read_csv("/content/drive/MyDrive/Topmentor/train.csv")
Train_data.head()

datetime  season  holiday  workingday  weather  temp   atemp  \
0  01-01-2011 00:00       1        0           0        1  9.84  14.395   
1  01-01-2011 01:00       1        0           0        1  9.02  13.635   
2  01-01-2011 02:00       1        0           0        1  9.02  13.635   
3  01-01-2011 03:00       1        0           0        1  9.84  14.395   
4  01-01-2011 04:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40  
2        80        0.0       5          27     32  
3        75        0.0       3          10     13  
4        75        0.0       0           1      1

In [ ]:
Test_data = pd.read_csv("/content/drive/MyDrive/Topmentor/test.csv")
Test_data.head()

datetime  season  holiday  workingday  weather   temp   atemp  \
0  30-06-2012 01:00       3        0           0        3  26.24  28.790   
1  30-06-2012 02:00       3        0           0        2  26.24  28.790   
2  30-06-2012 03:00       3        0           0        2  26.24  28.790   
3  30-06-2012 04:00       3        0           0        2  25.42  27.275   
4  30-06-2012 05:00       3        0           0        1  26.24  28.790   

   humidity  windspeed  casual  registered  
0        89    15.0013       3          55  
1        89     0.0000       7          54  
2        89     0.0000       3          20  
3        94     0.0000       3          15  
4        89    11.0014       3           7

In [ ]:
Train_data['datetime'] = pd.to_datetime(Train_data['datetime'], format='%d-%m-%Y %H:%M', errors='coerce')
Train_data['hour'] = Train_data['datetime'].dt.hour
Train_data['day'] = Train_data['datetime'].dt.day
Train_data['month'] = Train_data['datetime'].dt.month
Train_data['year'] = Train_data['datetime'].dt.year
Train_data['month'] = Train_data['datetime'].dt.month
Train_data['year'] = Train_data['datetime'].dt.year

In [ ]:
Train_data['weekday'] = Train_data['datetime'].dt.dayofweek

In [ ]:
X = Train_data[['season', 'holiday', 'workingday', 'weather', 'temp', 'atemp', 'humidity', 'windspeed', 'hour', 'day', 'month', 'year', 'weekday']]
y = Train_data['count']


In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=123)

model = RandomForestRegressor(n_estimators=100, random_state=123)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=123)

In [ ]:
pred = model.predict(X_val)

In [ ]:
pred

array([603.12,  63.78,   4.7 , ..., 432.12,  14.61,   5.22])

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, mean_squared_log_error

In [ ]:
r2_score(y_val, predictions)

0.947480323193749

In [ ]:
mean_absolute_error(y_val, predictions)


22.68615562403698

In [ ]:
mean_squared_error(y_val,predictions)

1369.7403042372882

In [ ]:
np.sqrt(mean_squared_log_error(y_val,predictions))

0.3264257820569494

In [ ]:
Test_pred = model.predict(X_val)
Test_pred

array([603.12,  63.78,   4.7 , ..., 432.12,  14.61,   5.22])

In [ ]:
final_pred = np.exp(Test_pred)
final_pred

<ipython-input-121-e79831e39039>:1: RuntimeWarning: overflow encountered in exp
  final_pred = np.exp(Test_pred)


array([8.54452501e+261, 5.00382435e+027, 1.09947172e+002, ...,
       4.64870000e+187, 2.21331068e+006, 1.84934184e+002])